
import { TripData, TripRecommendation } from "./types";

/**
 * Maps categories or keywords to specific KML icon styles.
 */
const getStyleId = (category: string, title: string, description: string): string => {
  const text = `${category} ${title} ${description}`.toLowerCase();
  
  // High-priority Category mapping
  if (text.includes('dining') || text.includes('food') || text.includes('restaurant')) return 'icon-dining';
  if (text.includes('landmark') || text.includes('sight') || text.includes('attraction') || text.includes('history')) return 'icon-camera';
  if (text.includes('nature') || text.includes('park') || text.includes('garden')) return 'icon-parks';
  if (text.includes('art') || text.includes('museum') || text.includes('gallery')) return 'icon-arts';
  if (text.includes('shop') || text.includes('market')) return 'icon-shopping';
  if (text.includes('nightlife') || text.includes('bar') || text.includes('club')) return 'icon-bars';

  return 'icon-camera';
};

/**
 * Generates the Style definitions for the KML header.
 */
const getKmlStyles = (): string => {
  const styles = [
    { id: 'icon-dining', url: 'http://maps.google.com/mapfiles/kml/shapes/dining.png' },
    { id: 'icon-parks', url: 'http://maps.google.com/mapfiles/kml/shapes/parks.png' },
    { id: 'icon-arts', url: 'http://maps.google.com/mapfiles/kml/shapes/arts.png' },
    { id: 'icon-shopping', url: 'http://maps.google.com/mapfiles/kml/shapes/shopping.png' },
    { id: 'icon-bars', url: 'http://maps.google.com/mapfiles/kml/shapes/bars.png' },
    { id: 'icon-camera', url: 'http://maps.google.com/mapfiles/kml/shapes/camera.png' },
    { id: 'icon-default', url: 'http://maps.google.com/mapfiles/kml/pushpin/blue-pushpin.png' },
  ];

  return styles.map(style => `
    <Style id="${style.id}">
      <IconStyle>
        <scale>1.2</scale>
        <Icon>
          <href>${style.url}</href>
        </Icon>
      </IconStyle>
    </Style>`).join('');
};

/**
 * Generates a KML string from the TripData object.
 */
export const generateKml = (data: TripData): string => {
  const planSuffix = "Trip Plan";
  const desc = "Personalized trip layers generated by MapLayer AI.";

  const header = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(data.city)} - ${planSuffix}</name>
    <description>${desc}</description>
    ${getKmlStyles()}`;

  const folders = data.layers.map(layer => {
    const placemarks = layer.places.map(place => {
      // Determine style for EACH individual place
      const styleId = getStyleId(place.category, place.title, place.description);
      
      const geometry = (place.lng !== undefined && place.lat !== undefined) 
        ? `<Point><coordinates>${place.lng},${place.lat},0</coordinates></Point>`
        : '';

      return `
      <Placemark>
        <name>${escapeXml(place.title)}</name>
        <description>${escapeXml(place.description)}</description>
        <styleUrl>#${styleId}</styleUrl>
        ${geometry}
        ${place.mapUrl ? `<ExtendedData><Data name="GoogleMapsURL"><value>${escapeXml(place.mapUrl)}</value></Data></ExtendedData>` : ''}
      </Placemark>`;
    }).join('');

    return `
    <Folder>
      <name>${escapeXml(layer.name)}</name>
      ${placemarks}
    </Folder>`;
  }).join('');

  const footer = `
  </Document>
</kml>`;

  return header + folders + footer;
};

const escapeXml = (unsafe: string): string => {
  if (!unsafe) return "";
  return unsafe.replace(/[<>&"']/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '"': return '&quot;';
      case "'": return '&apos;';
      default: return c;
    }
  });
};

export const downloadFile = (content: string, fileName: string, contentType: string) => {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
};
