
import { TripData } from "./types";
import { getDefaultKmlIcon } from "./helpers/kmlIconHelper";

/**
 * Maps categories to specific KML icon styles using shared constants.
 */
const getStyleId = (category: string, title: string, description: string): string => {
  return getDefaultKmlIcon({ category, title, description });
};

/**
 * Generates the Style definitions for the KML header.
 */
const getKmlStyles = (): string => {
  const styles = [
    { id: 'icon-dining', url: 'https://i.postimg.cc/WFrK5FCT/image.png' },
    { id: 'icon-arts', url: 'https://i.postimg.cc/64rkp2fL/image.png' },
    { id: 'icon-shopping', url: 'https://i.postimg.cc/w7JvD00S/image.png' },
    { id: 'icon-bars', url: 'https://i.postimg.cc/ygFQmq3f/image.png' },
    { id: 'icon-camera', url: 'https://i.postimg.cc/zbtLPvhZ/image.png' },
    { id: 'icon-beach', url: 'https://i.postimg.cc/629RmF1Q/image.png' },
    { id: 'icon-hotel', url: 'https://i.postimg.cc/kBZHPyCm/image.png' },
    { id: 'icon-icecream', url: 'https://i.postimg.cc/DJgQf7bq/image.png' },
    { id: 'icon-coffee', url: 'https://i.postimg.cc/2bfT8H9r/image.png' },
    { id: 'icon-default', url: 'http://maps.google.com/mapfiles/kml/pushpin/blue-pushpin.png' },
  ];

  return styles.map(style => `
    <Style id="${style.id}">
      <IconStyle>
        <scale>1.2</scale>
        <Icon>
          <href>${style.url}</href>
        </Icon>
      </IconStyle>
    </Style>`).join('');
};

/**
 * Generates a KML string from the TripData object.
 */
export const generateKml = (data: TripData): string => {
  const planSuffix = "Trip Plan";
  const desc = "Personalized trip layers generated by MapLayer AI.";

  const header = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(data.city)} - ${planSuffix}</name>
    <description>${desc}</description>
    ${getKmlStyles()}`;

  const folders = data.layers.map(layer => {
    const placemarks = layer.places.map(place => {
      // Use custom icon if set, otherwise determine from category
      const styleId = place.customKmlIcon || getStyleId(place.category, place.title, place.description);
      
      const geometry = (place.lng !== undefined && place.lat !== undefined) 
        ? `<Point><coordinates>${place.lng},${place.lat},0</coordinates></Point>`
        : '';

      // ExtendedData is the only field Google My Maps reliably preserves
      // verbatim across a round-trip. We stash IconId here so re-import can
      // restore the original icon even when Google rewrites styleUrl/icon hrefs.
      const extendedDataEntries = [
        `<Data name="IconId"><value>${escapeXml(styleId)}</value></Data>`,
        place.mapUrl ? `<Data name="GoogleMapsURL"><value>${escapeXml(place.mapUrl)}</value></Data>` : '',
      ].filter(Boolean).join('');

      return `
      <Placemark>
        <name>${escapeXml(place.title)}</name>
        <description>${escapeXml(place.description)}</description>
        <styleUrl>#${styleId}</styleUrl>
        ${geometry}
        <ExtendedData>${extendedDataEntries}</ExtendedData>
      </Placemark>`;
    }).join('');

    return `
    <Folder>
      <name>${escapeXml(layer.name)}</name>
      ${placemarks}
    </Folder>`;
  }).join('');

  const footer = `
  </Document>
</kml>`;

  return header + folders + footer;
};

const escapeXml = (unsafe: string): string => {
  if (!unsafe) return "";
  return unsafe.replace(/[<>&"']/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '"': return '&quot;';
      case "'": return '&apos;';
      default: return c;
    }
  });
};

export const downloadFile = (content: string, fileName: string, contentType: string) => {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
};
