
import { TripData, TripRecommendation } from "./types";
import { CATEGORY_RULES, KML_ICON_STYLES } from "./constants";

/**
 * Maps categories to specific KML icon styles using shared constants.
 */
const getStyleId = (category: string, title: string, description: string): string => {
  // First, try to get icon directly from the category name
  if (category && KML_ICON_STYLES[category]) {
    return KML_ICON_STYLES[category];
  }
  
  // Fallback: search in text for keyword matching
  const text = `${category} ${title} ${description}`.toLowerCase();
  
  // Check specific categories first - Hotels before Bar to avoid hotels with bars being categorized as bars
  const priorityOrder = ['Tourist Attractions', 'Hotels', 'Restaurants', 'Bar', 'Museums & Galleries', 'Shopping', 'Beach'];
  
  for (const categoryName of priorityOrder) {
    const keywords = CATEGORY_RULES[categoryName];
    if (keywords && keywords.some(keyword => text.includes(keyword))) {
      return KML_ICON_STYLES[categoryName] || 'icon-camera';
    }
  }
  
  return 'icon-camera';
};

/**
 * Generates the Style definitions for the KML header.
 */
const getKmlStyles = (): string => {
  const styles = [
    { id: 'icon-dining', url: 'https://i.postimg.cc/WFrK5FCT/image.png' },
    { id: 'icon-parks', url: 'http://maps.google.com/mapfiles/kml/shapes/parks.png' },
    { id: 'icon-arts', url: 'https://i.postimg.cc/64rkp2fL/image.png' },
    { id: 'icon-shopping', url: 'https://i.postimg.cc/w7JvD00S/image.png' },
    { id: 'icon-bars', url: 'https://i.postimg.cc/ygFQmq3f/image.png' },
    { id: 'icon-camera', url: 'https://i.postimg.cc/zbtLPvhZ/image.png' },
    { id: 'icon-beach', url: 'https://i.postimg.cc/629RmF1Q/image.png' },
    { id: 'icon-hotel', url: 'https://i.postimg.cc/kBZHPyCm/image.png' },
    { id: 'icon-icecream', url: 'https://i.postimg.cc/DJgQf7bq/image.png' },
    { id: 'icon-coffee', url: 'https://i.postimg.cc/2bfT8H9r/image.png' },
    { id: 'icon-default', url: 'http://maps.google.com/mapfiles/kml/pushpin/blue-pushpin.png' },
  ];

  return styles.map(style => `
    <Style id="${style.id}">
      <IconStyle>
        <scale>1.2</scale>
        <Icon>
          <href>${style.url}</href>
        </Icon>
      </IconStyle>
    </Style>`).join('');
};

/**
 * Generates a KML string from the TripData object.
 */
export const generateKml = (data: TripData): string => {
  const planSuffix = "Trip Plan";
  const desc = "Personalized trip layers generated by MapLayer AI.";

  const header = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(data.city)} - ${planSuffix}</name>
    <description>${desc}</description>
    ${getKmlStyles()}`;

  const folders = data.layers.map(layer => {
    const placemarks = layer.places.map(place => {
      // Use custom icon if set, otherwise determine from category
      const styleId = place.customKmlIcon || getStyleId(place.category, place.title, place.description);
      
      const geometry = (place.lng !== undefined && place.lat !== undefined) 
        ? `<Point><coordinates>${place.lng},${place.lat},0</coordinates></Point>`
        : '';

      return `
      <Placemark>
        <name>${escapeXml(place.title)}</name>
        <description>${escapeXml(place.description)}</description>
        <styleUrl>#${styleId}</styleUrl>
        ${geometry}
        ${place.mapUrl ? `<ExtendedData><Data name="GoogleMapsURL"><value>${escapeXml(place.mapUrl)}</value></Data></ExtendedData>` : ''}
      </Placemark>`;
    }).join('');

    return `
    <Folder>
      <name>${escapeXml(layer.name)}</name>
      ${placemarks}
    </Folder>`;
  }).join('');

  const footer = `
  </Document>
</kml>`;

  return header + folders + footer;
};

const escapeXml = (unsafe: string): string => {
  if (!unsafe) return "";
  return unsafe.replace(/[<>&"']/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '"': return '&quot;';
      case "'": return '&apos;';
      default: return c;
    }
  });
};

export const downloadFile = (content: string, fileName: string, contentType: string) => {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
};
