export const saveStatusStyles = {
  banner: 'border rounded-xl p-4 shadow-sm',
  bannerAuth: 'bg-indigo-50 border-indigo-200',
  bannerError: 'bg-amber-50 border-amber-200',
  inner: 'flex items-start gap-3',
  iconWrap: 'flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center text-lg',
  iconWrapAuth: 'bg-indigo-100',
  iconWrapError: 'bg-amber-100',
  body: 'flex-1',
  title: 'text-sm font-bold mb-1',
  titleAuth: 'text-indigo-900',
  titleError: 'text-amber-900',
  text: 'text-xs',
  textAuth: 'text-indigo-800',
  textError: 'text-amber-800',
  actions: 'mt-2 flex gap-2',
  primaryBtn: 'px-3 py-1.5 rounded-lg text-xs font-semibold text-white transition-colors',
  primaryBtnAuth: 'bg-indigo-600 hover:bg-indigo-700',
  primaryBtnError: 'bg-amber-600 hover:bg-amber-700',
  close: 'text-xl leading-none',
  closeAuth: 'text-indigo-400 hover:text-indigo-600',
  closeError: 'text-amber-400 hover:text-amber-600',
} as const;
